apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: grid
spec:
  version: "v0.0.1"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/replicatedhq/kubectl-grid/releases/download/v0.0.1/grid_0.0.1_linux_amd64-0.0.1.tar.gz
    sha256: "4489859d4be491f210bad20f09889a9a33654b91576401742c29b4f32b68ec5a"
    files:
    - from: grid
      to: .
    - from: LICENSE
      to: .
    bin: grid
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/replicatedhq/kubectl-grid/releases/download/v0.0.1/grid_0.0.1_darwin_amd64-0.0.1.tar.gz
    sha256: "d887b9acdbd2fdd3e06f0b3103436c7c9257ce252758cd456233df3c9033d4f0"
    files:
    - from: grid
      to: .
    - from: LICENSE
      to: .
    bin: grid
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/replicatedhq/kubectl-grid/releases/download/v0.0.1/grid_0.0.1_windows_amd64-0.0.1.zip
    sha256: "278b8e2d45f4e9a9df20e6bd863eb867668ad7432b248e088f74b9ab41493823"
    files:
    - from: grid.exe
      to: .
    - from: LICENSE
      to: .
    bin: grid.exe
  shortDescription: description
  homepage: https://github.com/replicatedhq/kubectl-grid
  caveats: |
    Usage:
      $ kubectl grid

    For additional options:
      $ kubectl grid --help
      or https://github.com/replicatedhq/kubectl-grid/blob/v0.0.1/doc/USAGE.md

  description: |
    The plugin will ...
